name: CI

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: loop & sleep
        run: |
          for i in {1..10}; do echo "sleeping for ${i}s..." && sleep $i; done
